// Auto generated by Craby. DO NOT EDIT.
#include <CxxGlimpseCoreModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::glimpsecore::modules::CxxGlimpseCoreModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::glimpsecore::modules::CxxGlimpseCoreModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_kr_ll3_glimpse_core_GlimpsecorePackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  const char* cDataPath = env->GetStringUTFChars(jDataPath, nullptr);
  auto dataPath = std::string(cDataPath);
  env->ReleaseStringUTFChars(jDataPath, cDataPath);
  craby::glimpsecore::modules::CxxGlimpseCoreModule::dataPath = dataPath;
}
