// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::glimpse_core_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::glimpsecore::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct NullableNumber {
        null: bool,
        val: f64,
    }

    #[derive(Clone)]
    struct NullableStringArray {
        null: bool,
        val: Vec<String>,
    }

    #[derive(Clone)]
    struct GlimpseInitializeReviewScheduleOutput {
        next_review_at: f64,
        stability: NullableNumber,
        difficulty: NullableNumber,
        last_reviewed_at: NullableNumber,
    }

    #[derive(Clone)]
    struct GlimpseCalculateNextReviewOutput {
        interval_ms: f64,
        next_review_at: f64,
    }

    extern "Rust" {
        type GlimpseCore;

        #[cxx_name = "createGlimpseCore"]
        fn create_glimpse_core(id: usize, data_path: &str) -> Box<GlimpseCore>;

        #[cxx_name = "calculateNextReview"]
        fn glimpse_core_calculate_next_review(it_: &mut GlimpseCore, last_reviewed_at: NullableNumber, next_review_at: NullableNumber, feedback_type: &str, now: f64) -> Result<GlimpseCalculateNextReviewOutput>;

        #[cxx_name = "calculateTagOverlap"]
        fn glimpse_core_calculate_tag_overlap(it_: &mut GlimpseCore, left_tags: NullableStringArray, right_tags: NullableStringArray) -> Result<f64>;

        #[cxx_name = "initializeReviewSchedule"]
        fn glimpse_core_initialize_review_schedule(it_: &mut GlimpseCore, created_at: f64, interval_ms: NullableNumber) -> Result<GlimpseInitializeReviewScheduleOutput>;
    }
}

fn create_glimpse_core(id: usize, data_path: &str) -> Box<GlimpseCore> {
    let ctx = Context::new(id, data_path);
    Box::new(GlimpseCore::new(ctx))
}

fn glimpse_core_calculate_next_review(it_: &mut GlimpseCore, last_reviewed_at: NullableNumber, next_review_at: NullableNumber, feedback_type: &str, now: f64) -> Result<GlimpseCalculateNextReviewOutput, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.calculate_next_review(last_reviewed_at.into(), next_review_at.into(), feedback_type, now);
        ret
    })
}

fn glimpse_core_calculate_tag_overlap(it_: &mut GlimpseCore, left_tags: NullableStringArray, right_tags: NullableStringArray) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.calculate_tag_overlap(left_tags.into(), right_tags.into());
        ret
    })
}

fn glimpse_core_initialize_review_schedule(it_: &mut GlimpseCore, created_at: f64, interval_ms: NullableNumber) -> Result<GlimpseInitializeReviewScheduleOutput, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.initialize_review_schedule(created_at, interval_ms.into());
        ret
    })
}


