// Auto generated by Craby. DO NOT EDIT.
// Hash: 8574b6d1de882de4
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait GlimpseCoreSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn calculate_next_review(&mut self, last_reviewed_at: Nullable<Number>, next_review_at: Nullable<Number>, feedback_type: &str, now: Number) -> GlimpseCalculateNextReviewOutput;
    fn calculate_tag_overlap(&mut self, left_tags: Nullable<Array<String>>, right_tags: Nullable<Array<String>>) -> Number;
    fn initialize_review_schedule(&mut self, created_at: Number, interval_ms: Nullable<Number>) -> GlimpseInitializeReviewScheduleOutput;
}

impl Default for NullableNumber {
    fn default() -> Self {
        NullableNumber {
            null: true,
            val: 0.0,
        }
    }
}

impl From<NullableNumber> for Nullable<Number> {
    fn from(val: NullableNumber) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<Number>> for NullableNumber {
    fn from(val: Nullable<Number>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableNumber {
            val: val.unwrap_or(0.0),
            null,
        }
    }
}

impl Default for NullableStringArray {
    fn default() -> Self {
        NullableStringArray {
            null: true,
            val: Vec::default(),
        }
    }
}

impl From<NullableStringArray> for Nullable<Array<String>> {
    fn from(val: NullableStringArray) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<Array<String>>> for NullableStringArray {
    fn from(val: Nullable<Array<String>>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableStringArray {
            val: val.unwrap_or(Vec::default()),
            null,
        }
    }
}

impl Default for GlimpseInitializeReviewScheduleOutput {
    fn default() -> Self {
        GlimpseInitializeReviewScheduleOutput {
            next_review_at: 0.0,
            stability: NullableNumber::default(),
            difficulty: NullableNumber::default(),
            last_reviewed_at: NullableNumber::default()
        }
    }
}

impl Default for GlimpseCalculateNextReviewOutput {
    fn default() -> Self {
        GlimpseCalculateNextReviewOutput {
            interval_ms: 0.0,
            next_review_at: 0.0
        }
    }
}
