/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as CaptureRouteImport } from './app/capture'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthenticatedSettingsRouteImport } from './app/_authenticated/settings'
import { Route as AuthenticatedReviewRouteImport } from './app/_authenticated/review'
import { Route as AuthenticatedGraphRouteImport } from './app/_authenticated/graph'
import { Route as AuthenticatedDigestRouteImport } from './app/_authenticated/digest'
import { Route as AuthenticatedLibraryIndexRouteImport } from './app/_authenticated/library/index'
import { Route as AuthenticatedChatIndexRouteImport } from './app/_authenticated/chat/index'
import { Route as AuthenticatedLibraryItemIdRouteImport } from './app/_authenticated/library/$itemId'
import { Route as AuthenticatedChatConversationIdRouteImport } from './app/_authenticated/chat/$conversationId'

const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDigestRoute = AuthenticatedDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryItemIdRoute =
  AuthenticatedLibraryItemIdRouteImport.update({
    id: '/library/$itemId',
    path: '/library/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/library/$itemId': typeof AuthenticatedLibraryItemIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/library/$itemId': typeof AuthenticatedLibraryItemIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/capture': typeof CaptureRoute
  '/_authenticated/digest': typeof AuthenticatedDigestRoute
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/library/$itemId': typeof AuthenticatedLibraryItemIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/digest'
    | '/graph'
    | '/review'
    | '/settings'
    | '/chat/$conversationId'
    | '/library/$itemId'
    | '/chat/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/digest'
    | '/graph'
    | '/review'
    | '/settings'
    | '/chat/$conversationId'
    | '/library/$itemId'
    | '/chat'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/capture'
    | '/_authenticated/digest'
    | '/_authenticated/graph'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/library/$itemId'
    | '/_authenticated/chat/'
    | '/_authenticated/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CaptureRoute: typeof CaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/digest': {
      id: '/_authenticated/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AuthenticatedDigestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/$itemId': {
      id: '/_authenticated/library/$itemId'
      path: '/library/$itemId'
      fullPath: '/library/$itemId'
      preLoaderRoute: typeof AuthenticatedLibraryItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDigestRoute: typeof AuthenticatedDigestRoute
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedLibraryItemIdRoute: typeof AuthenticatedLibraryItemIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDigestRoute: AuthenticatedDigestRoute,
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedLibraryItemIdRoute: AuthenticatedLibraryItemIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CaptureRoute: CaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
