// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::glimpse_core_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::glimpsecore::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct NullableNumber {
        null: bool,
        val: f64,
    }

    #[derive(Clone)]
    struct NullableStringArray {
        null: bool,
        val: Vec<String>,
    }

    #[derive(Clone)]
    struct GlimpseInitializeReviewScheduleOutput {
        next_review_at: f64,
        stability: NullableNumber,
        difficulty: NullableNumber,
        last_reviewed_at: NullableNumber,
    }

    #[derive(Clone)]
    struct GlimpseCalculateNextReviewOutput {
        interval_ms: f64,
        next_review_at: f64,
    }

    extern "Rust" {
        type GlimpseCore;

        #[cxx_name = "createGlimpseCore"]
        fn create_glimpse_core(id: usize, data_path: &str) -> Box<GlimpseCore>;

        #[cxx_name = "addMessageJson"]
        fn glimpse_core_add_message_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String>;

        #[cxx_name = "calculateNextReview"]
        fn glimpse_core_calculate_next_review(it_: &mut GlimpseCore, last_reviewed_at: NullableNumber, next_review_at: NullableNumber, feedback_type: &str, now: f64) -> Result<GlimpseCalculateNextReviewOutput>;

        #[cxx_name = "calculateTagOverlap"]
        fn glimpse_core_calculate_tag_overlap(it_: &mut GlimpseCore, left_tags: NullableStringArray, right_tags: NullableStringArray) -> Result<f64>;

        #[cxx_name = "createConversationJson"]
        fn glimpse_core_create_conversation_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String>;

        #[cxx_name = "deleteConversation"]
        fn glimpse_core_delete_conversation(it_: &mut GlimpseCore, conversation_id: &str, deleted_at: f64) -> Result<()>;

        #[cxx_name = "deleteMessage"]
        fn glimpse_core_delete_message(it_: &mut GlimpseCore, message_id: &str, deleted_at: f64) -> Result<()>;

        #[cxx_name = "getDueKnowledgeItemsJson"]
        fn glimpse_core_get_due_knowledge_items_json(it_: &mut GlimpseCore, now: f64, limit: NullableNumber) -> Result<String>;

        #[cxx_name = "getKnowledgeItemByIdJson"]
        fn glimpse_core_get_knowledge_item_by_id_json(it_: &mut GlimpseCore, item_id: &str) -> Result<String>;

        #[cxx_name = "initializeReviewSchedule"]
        fn glimpse_core_initialize_review_schedule(it_: &mut GlimpseCore, created_at: f64, interval_ms: NullableNumber) -> Result<GlimpseInitializeReviewScheduleOutput>;

        #[cxx_name = "listConversationMessagesJson"]
        fn glimpse_core_list_conversation_messages_json(it_: &mut GlimpseCore, conversation_id: &str) -> Result<String>;

        #[cxx_name = "listConversationsJson"]
        fn glimpse_core_list_conversations_json(it_: &mut GlimpseCore) -> Result<String>;

        #[cxx_name = "listKnowledgeItemsByIdsJson"]
        fn glimpse_core_list_knowledge_items_by_ids_json(it_: &mut GlimpseCore, item_ids_json: &str) -> Result<String>;

        #[cxx_name = "listKnowledgeItemsJson"]
        fn glimpse_core_list_knowledge_items_json(it_: &mut GlimpseCore) -> Result<String>;

        #[cxx_name = "listPendingKnowledgeItemsForLabelingJson"]
        fn glimpse_core_list_pending_knowledge_items_for_labeling_json(it_: &mut GlimpseCore, limit: f64) -> Result<String>;

        #[cxx_name = "listPendingRecommendationsJson"]
        fn glimpse_core_list_pending_recommendations_json(it_: &mut GlimpseCore) -> Result<String>;

        #[cxx_name = "listRecentFeedbackEventsJson"]
        fn glimpse_core_list_recent_feedback_events_json(it_: &mut GlimpseCore, limit: f64) -> Result<String>;

        #[cxx_name = "listRecommendationsJson"]
        fn glimpse_core_list_recommendations_json(it_: &mut GlimpseCore) -> Result<String>;

        #[cxx_name = "listWeeklyKnowledgeItemsJson"]
        fn glimpse_core_list_weekly_knowledge_items_json(it_: &mut GlimpseCore, since: f64) -> Result<String>;

        #[cxx_name = "logRecommendationFeedbackJson"]
        fn glimpse_core_log_recommendation_feedback_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String>;

        #[cxx_name = "respondToRecommendationJson"]
        fn glimpse_core_respond_to_recommendation_json(it_: &mut GlimpseCore, recommendation_id: &str, status: &str, event_json: &str) -> Result<()>;

        #[cxx_name = "saveKnowledgeItemJson"]
        fn glimpse_core_save_knowledge_item_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String>;

        #[cxx_name = "saveRecommendationsJson"]
        fn glimpse_core_save_recommendations_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<()>;

        #[cxx_name = "updateConversationJson"]
        fn glimpse_core_update_conversation_json(it_: &mut GlimpseCore, conversation_id: &str, patch_json: &str) -> Result<String>;

        #[cxx_name = "updateKnowledgeItemJson"]
        fn glimpse_core_update_knowledge_item_json(it_: &mut GlimpseCore, item_id: &str, patch_json: &str) -> Result<String>;

        #[cxx_name = "updateMessageJson"]
        fn glimpse_core_update_message_json(it_: &mut GlimpseCore, message_id: &str, patch_json: &str) -> Result<String>;
    }
}

fn create_glimpse_core(id: usize, data_path: &str) -> Box<GlimpseCore> {
    let ctx = Context::new(id, data_path);
    Box::new(GlimpseCore::new(ctx))
}

fn glimpse_core_add_message_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add_message_json(payload_json);
        ret
    })
}

fn glimpse_core_calculate_next_review(it_: &mut GlimpseCore, last_reviewed_at: NullableNumber, next_review_at: NullableNumber, feedback_type: &str, now: f64) -> Result<GlimpseCalculateNextReviewOutput, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.calculate_next_review(last_reviewed_at.into(), next_review_at.into(), feedback_type, now);
        ret
    })
}

fn glimpse_core_calculate_tag_overlap(it_: &mut GlimpseCore, left_tags: NullableStringArray, right_tags: NullableStringArray) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.calculate_tag_overlap(left_tags.into(), right_tags.into());
        ret
    })
}

fn glimpse_core_create_conversation_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.create_conversation_json(payload_json);
        ret
    })
}

fn glimpse_core_delete_conversation(it_: &mut GlimpseCore, conversation_id: &str, deleted_at: f64) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.delete_conversation(conversation_id, deleted_at);
        ret
    })
}

fn glimpse_core_delete_message(it_: &mut GlimpseCore, message_id: &str, deleted_at: f64) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.delete_message(message_id, deleted_at);
        ret
    })
}

fn glimpse_core_get_due_knowledge_items_json(it_: &mut GlimpseCore, now: f64, limit: NullableNumber) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get_due_knowledge_items_json(now, limit.into());
        ret
    })
}

fn glimpse_core_get_knowledge_item_by_id_json(it_: &mut GlimpseCore, item_id: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get_knowledge_item_by_id_json(item_id);
        ret
    })
}

fn glimpse_core_initialize_review_schedule(it_: &mut GlimpseCore, created_at: f64, interval_ms: NullableNumber) -> Result<GlimpseInitializeReviewScheduleOutput, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.initialize_review_schedule(created_at, interval_ms.into());
        ret
    })
}

fn glimpse_core_list_conversation_messages_json(it_: &mut GlimpseCore, conversation_id: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_conversation_messages_json(conversation_id);
        ret
    })
}

fn glimpse_core_list_conversations_json(it_: &mut GlimpseCore) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_conversations_json();
        ret
    })
}

fn glimpse_core_list_knowledge_items_by_ids_json(it_: &mut GlimpseCore, item_ids_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_knowledge_items_by_ids_json(item_ids_json);
        ret
    })
}

fn glimpse_core_list_knowledge_items_json(it_: &mut GlimpseCore) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_knowledge_items_json();
        ret
    })
}

fn glimpse_core_list_pending_knowledge_items_for_labeling_json(it_: &mut GlimpseCore, limit: f64) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_pending_knowledge_items_for_labeling_json(limit);
        ret
    })
}

fn glimpse_core_list_pending_recommendations_json(it_: &mut GlimpseCore) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_pending_recommendations_json();
        ret
    })
}

fn glimpse_core_list_recent_feedback_events_json(it_: &mut GlimpseCore, limit: f64) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_recent_feedback_events_json(limit);
        ret
    })
}

fn glimpse_core_list_recommendations_json(it_: &mut GlimpseCore) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_recommendations_json();
        ret
    })
}

fn glimpse_core_list_weekly_knowledge_items_json(it_: &mut GlimpseCore, since: f64) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.list_weekly_knowledge_items_json(since);
        ret
    })
}

fn glimpse_core_log_recommendation_feedback_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.log_recommendation_feedback_json(payload_json);
        ret
    })
}

fn glimpse_core_respond_to_recommendation_json(it_: &mut GlimpseCore, recommendation_id: &str, status: &str, event_json: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.respond_to_recommendation_json(recommendation_id, status, event_json);
        ret
    })
}

fn glimpse_core_save_knowledge_item_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.save_knowledge_item_json(payload_json);
        ret
    })
}

fn glimpse_core_save_recommendations_json(it_: &mut GlimpseCore, payload_json: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.save_recommendations_json(payload_json);
        ret
    })
}

fn glimpse_core_update_conversation_json(it_: &mut GlimpseCore, conversation_id: &str, patch_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.update_conversation_json(conversation_id, patch_json);
        ret
    })
}

fn glimpse_core_update_knowledge_item_json(it_: &mut GlimpseCore, item_id: &str, patch_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.update_knowledge_item_json(item_id, patch_json);
        ret
    })
}

fn glimpse_core_update_message_json(it_: &mut GlimpseCore, message_id: &str, patch_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.update_message_json(message_id, patch_json);
        ret
    })
}


