// Auto generated by Craby. DO NOT EDIT.
// Hash: c82d421a139b6ba6
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait GlimpseCoreSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn add_message_json(&mut self, payload_json: &str) -> String;
    fn calculate_next_review(&mut self, last_reviewed_at: Nullable<Number>, next_review_at: Nullable<Number>, feedback_type: &str, now: Number) -> GlimpseCalculateNextReviewOutput;
    fn calculate_tag_overlap(&mut self, left_tags: Nullable<Array<String>>, right_tags: Nullable<Array<String>>) -> Number;
    fn create_conversation_json(&mut self, payload_json: &str) -> String;
    fn delete_conversation(&mut self, conversation_id: &str, deleted_at: Number) -> Void;
    fn delete_message(&mut self, message_id: &str, deleted_at: Number) -> Void;
    fn get_due_knowledge_items_json(&mut self, now: Number, limit: Nullable<Number>) -> String;
    fn get_knowledge_item_by_id_json(&mut self, item_id: &str) -> String;
    fn initialize_review_schedule(&mut self, created_at: Number, interval_ms: Nullable<Number>) -> GlimpseInitializeReviewScheduleOutput;
    fn list_conversation_messages_json(&mut self, conversation_id: &str) -> String;
    fn list_conversations_json(&mut self) -> String;
    fn list_knowledge_items_by_ids_json(&mut self, item_ids_json: &str) -> String;
    fn list_knowledge_items_json(&mut self) -> String;
    fn list_pending_knowledge_items_for_labeling_json(&mut self, limit: Number) -> String;
    fn list_pending_recommendations_json(&mut self) -> String;
    fn list_recent_feedback_events_json(&mut self, limit: Number) -> String;
    fn list_recommendations_json(&mut self) -> String;
    fn list_weekly_knowledge_items_json(&mut self, since: Number) -> String;
    fn log_recommendation_feedback_json(&mut self, payload_json: &str) -> String;
    fn respond_to_recommendation_json(&mut self, recommendation_id: &str, status: &str, event_json: &str) -> Void;
    fn save_knowledge_item_json(&mut self, payload_json: &str) -> String;
    fn save_recommendations_json(&mut self, payload_json: &str) -> Void;
    fn update_conversation_json(&mut self, conversation_id: &str, patch_json: &str) -> String;
    fn update_knowledge_item_json(&mut self, item_id: &str, patch_json: &str) -> String;
    fn update_message_json(&mut self, message_id: &str, patch_json: &str) -> String;
}

impl Default for NullableNumber {
    fn default() -> Self {
        NullableNumber {
            null: true,
            val: 0.0,
        }
    }
}

impl From<NullableNumber> for Nullable<Number> {
    fn from(val: NullableNumber) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<Number>> for NullableNumber {
    fn from(val: Nullable<Number>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableNumber {
            val: val.unwrap_or(0.0),
            null,
        }
    }
}

impl Default for NullableStringArray {
    fn default() -> Self {
        NullableStringArray {
            null: true,
            val: Vec::default(),
        }
    }
}

impl From<NullableStringArray> for Nullable<Array<String>> {
    fn from(val: NullableStringArray) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<Array<String>>> for NullableStringArray {
    fn from(val: Nullable<Array<String>>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableStringArray {
            val: val.unwrap_or(Vec::default()),
            null,
        }
    }
}

impl Default for GlimpseInitializeReviewScheduleOutput {
    fn default() -> Self {
        GlimpseInitializeReviewScheduleOutput {
            next_review_at: 0.0,
            stability: NullableNumber::default(),
            difficulty: NullableNumber::default(),
            last_reviewed_at: NullableNumber::default()
        }
    }
}

impl Default for GlimpseCalculateNextReviewOutput {
    fn default() -> Self {
        GlimpseCalculateNextReviewOutput {
            interval_ms: 0.0,
            next_review_at: 0.0
        }
    }
}
