// Auto generated by Craby. DO NOT EDIT.
#include "CxxGlimpseCoreModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace glimpsecore {
namespace modules {

std::string CxxGlimpseCoreModule::dataPath = std::string();

CxxGlimpseCoreModule::CxxGlimpseCoreModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxGlimpseCoreModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::glimpsecore::bridging::GlimpseCore>(
    craby::glimpsecore::bridging::createGlimpseCore(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::glimpsecore::bridging::GlimpseCore *ptr) { rust::Box<craby::glimpsecore::bridging::GlimpseCore>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::glimpsecore::utils::ThreadPool>(10);
  methodMap_["addMessageJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::addMessageJson};
  methodMap_["calculateNextReview"] = MethodMetadata{4, &CxxGlimpseCoreModule::calculateNextReview};
  methodMap_["calculateTagOverlap"] = MethodMetadata{2, &CxxGlimpseCoreModule::calculateTagOverlap};
  methodMap_["createConversationJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::createConversationJson};
  methodMap_["deleteConversation"] = MethodMetadata{2, &CxxGlimpseCoreModule::deleteConversation};
  methodMap_["deleteMessage"] = MethodMetadata{2, &CxxGlimpseCoreModule::deleteMessage};
  methodMap_["getDueKnowledgeItemsJson"] = MethodMetadata{2, &CxxGlimpseCoreModule::getDueKnowledgeItemsJson};
  methodMap_["getKnowledgeItemByIdJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::getKnowledgeItemByIdJson};
  methodMap_["initializeReviewSchedule"] = MethodMetadata{2, &CxxGlimpseCoreModule::initializeReviewSchedule};
  methodMap_["listConversationMessagesJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::listConversationMessagesJson};
  methodMap_["listConversationsJson"] = MethodMetadata{0, &CxxGlimpseCoreModule::listConversationsJson};
  methodMap_["listKnowledgeItemsByIdsJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::listKnowledgeItemsByIdsJson};
  methodMap_["listKnowledgeItemsJson"] = MethodMetadata{0, &CxxGlimpseCoreModule::listKnowledgeItemsJson};
  methodMap_["listPendingKnowledgeItemsForLabelingJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::listPendingKnowledgeItemsForLabelingJson};
  methodMap_["listPendingRecommendationsJson"] = MethodMetadata{0, &CxxGlimpseCoreModule::listPendingRecommendationsJson};
  methodMap_["listRecentFeedbackEventsJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::listRecentFeedbackEventsJson};
  methodMap_["listRecommendationsJson"] = MethodMetadata{0, &CxxGlimpseCoreModule::listRecommendationsJson};
  methodMap_["listWeeklyKnowledgeItemsJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::listWeeklyKnowledgeItemsJson};
  methodMap_["logRecommendationFeedbackJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::logRecommendationFeedbackJson};
  methodMap_["respondToRecommendationJson"] = MethodMetadata{3, &CxxGlimpseCoreModule::respondToRecommendationJson};
  methodMap_["saveKnowledgeItemJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::saveKnowledgeItemJson};
  methodMap_["saveRecommendationsJson"] = MethodMetadata{1, &CxxGlimpseCoreModule::saveRecommendationsJson};
  methodMap_["updateConversationJson"] = MethodMetadata{2, &CxxGlimpseCoreModule::updateConversationJson};
  methodMap_["updateKnowledgeItemJson"] = MethodMetadata{2, &CxxGlimpseCoreModule::updateKnowledgeItemJson};
  methodMap_["updateMessageJson"] = MethodMetadata{2, &CxxGlimpseCoreModule::updateMessageJson};
}

CxxGlimpseCoreModule::~CxxGlimpseCoreModule() {
  invalidate();
}

void CxxGlimpseCoreModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxGlimpseCoreModule::addMessageJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::addMessageJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::calculateNextReview(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (4 != count) {
      throw jsi::JSError(rt, "Expected 4 arguments");
    }

    auto arg0 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[1], callInvoker);
    auto arg2$raw = args[2].asString(rt).utf8(rt);
    auto arg2 = rust::Str(arg2$raw.data(), arg2$raw.size());
    auto arg3 = react::bridging::fromJs<double>(rt, args[3], callInvoker);
    auto ret = craby::glimpsecore::bridging::calculateNextReview(*it_, arg0, arg1, arg2, arg3);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::calculateTagOverlap(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableStringArray>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableStringArray>(rt, args[1], callInvoker);
    auto ret = craby::glimpsecore::bridging::calculateTagOverlap(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::createConversationJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::createConversationJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::deleteConversation(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    craby::glimpsecore::bridging::deleteConversation(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::deleteMessage(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    craby::glimpsecore::bridging::deleteMessage(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::getDueKnowledgeItemsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[1], callInvoker);
    auto ret = craby::glimpsecore::bridging::getDueKnowledgeItemsJson(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::getKnowledgeItemByIdJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::getKnowledgeItemByIdJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::initializeReviewSchedule(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[1], callInvoker);
    auto ret = craby::glimpsecore::bridging::initializeReviewSchedule(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listConversationMessagesJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::listConversationMessagesJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listConversationsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::glimpsecore::bridging::listConversationsJson(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listKnowledgeItemsByIdsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::listKnowledgeItemsByIdsJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listKnowledgeItemsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::glimpsecore::bridging::listKnowledgeItemsJson(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listPendingKnowledgeItemsForLabelingJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto ret = craby::glimpsecore::bridging::listPendingKnowledgeItemsForLabelingJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listPendingRecommendationsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::glimpsecore::bridging::listPendingRecommendationsJson(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listRecentFeedbackEventsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto ret = craby::glimpsecore::bridging::listRecentFeedbackEventsJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listRecommendationsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::glimpsecore::bridging::listRecommendationsJson(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::listWeeklyKnowledgeItemsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto ret = craby::glimpsecore::bridging::listWeeklyKnowledgeItemsJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::logRecommendationFeedbackJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::logRecommendationFeedbackJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::respondToRecommendationJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (3 != count) {
      throw jsi::JSError(rt, "Expected 3 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    auto arg2$raw = args[2].asString(rt).utf8(rt);
    auto arg2 = rust::Str(arg2$raw.data(), arg2$raw.size());
    craby::glimpsecore::bridging::respondToRecommendationJson(*it_, arg0, arg1, arg2);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::saveKnowledgeItemJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::glimpsecore::bridging::saveKnowledgeItemJson(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::saveRecommendationsJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    craby::glimpsecore::bridging::saveRecommendationsJson(*it_, arg0);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::updateConversationJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    auto ret = craby::glimpsecore::bridging::updateConversationJson(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::updateKnowledgeItemJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    auto ret = craby::glimpsecore::bridging::updateKnowledgeItemJson(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::updateMessageJson(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    auto ret = craby::glimpsecore::bridging::updateMessageJson(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace glimpsecore
} // namespace craby
