/** @deprecated Import new application-layer code from `@glimpse/features`. */
export {
  calculateTagOverlap,
  createGenerateRecommendations,
  createGetPendingRecommendations,
  createGetRecentFeedbackEvents,
  createGetWeeklyItems,
  createLogRecommendationFeedback,
  createRespondToRecommendation,
  createSaveRecommendations,
} from '@glimpse/features';
export type {
  GenerateRecommendationsDeps,
  GenerateRecommendationsDepsResult,
  GenerateRecommendationsResult,
  GenerateFailureResult,
  GenerateResult,
  GeneratedRecommendation,
  GetPendingRecommendationsDeps,
  GetPendingResult,
  PendingFailureResult,
  PendingResult,
  PendingSuccessResult,
  GetRecentFeedbackResult,
  GetWeeklyItemsDeps,
  LogRecommendationFeedbackResult,
  LogFeedbackFailureResult,
  LogFeedbackResult,
  LogFeedbackSuccessResult,
  RecommendationFeedbackDeps,
  RecommendationSaveResult,
  RecommendationWithItems,
  RecentFeedbackFailureResult,
  RecentFeedbackResult,
  RecentFeedbackSuccessResult,
  RespondFailureResult,
  RespondResult,
  RespondSuccessResult,
  RespondToRecommendationDeps,
  RespondToRecommendationResult,
  SaveRecommendationsDeps,
  WeeklyItemsResult,
  WeeklyItemsFailureResult,
  WeeklyItemsSuccessResult,
} from '@glimpse/features';
