// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "cxx.h"
#include "ffi.rs.h"
#include <react/bridging/Bridging.h>
#include <variant>
#include <iterator>
#include <algorithm>

using namespace facebook;

namespace glimpsecore {

class RustVecBuffer : public jsi::MutableBuffer {
public:
  explicit RustVecBuffer(rust::Vec<uint8_t> vec)
    : vec_(std::move(vec)) {}

  ~RustVecBuffer() override = default;

  size_t size() const override {
    return vec_.size();
  }

  uint8_t* data() override {
    return const_cast<uint8_t*>(vec_.data());
  }

private:
  rust::Vec<uint8_t> vec_;
};

} // namespace glimpsecore

namespace facebook {
namespace react {

template <>
struct Bridging<std::monostate> {
  static std::monostate fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    return std::monostate{};
  }

  static jsi::Value toJs(jsi::Runtime& rt, const std::monostate& value) {
    return jsi::Value::undefined();
  }
};

template <>
struct Bridging<rust::Str> {
  static rust::Str fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::Str(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Str& value) {
    return react::bridging::toJs(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::String> {
  static rust::String fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::String(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::String& value) {
    return react::bridging::toJs(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::Vec<uint8_t>> {
  static rust::Vec<uint8_t> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arrayBuffer = value.asObject(rt).getArrayBuffer(rt);
    uint8_t* data = arrayBuffer.data(rt);
    size_t size = arrayBuffer.size(rt);
    rust::Vec<uint8_t> vec;
    vec.reserve(size);

    std::copy(data, data + size, std::back_inserter(vec));

    return vec;
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Vec<uint8_t>& vec) {
    auto buffer = std::make_shared<glimpsecore::RustVecBuffer>(std::move(vec));
    return jsi::ArrayBuffer(rt, buffer);
  }
};

template <typename T>
struct Bridging<rust::Vec<T>> {
  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> vec;
    vec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto element = arr.getValueAtIndex(rt, i);
      vec.push_back(react::bridging::fromJs<T>(rt, element, callInvoker));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto jsElement = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, jsElement);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::glimpsecore::bridging::GlimpseCalculateNextReviewOutput> {
  static craby::glimpsecore::bridging::GlimpseCalculateNextReviewOutput fromJs(
      jsi::Runtime &rt,
      const jsi::Value &value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$intervalMs = obj.getProperty(rt, "intervalMs");
    auto obj$nextReviewAt = obj.getProperty(rt, "nextReviewAt");

    auto _obj$intervalMs = react::bridging::fromJs<double>(rt, obj$intervalMs, callInvoker);
    auto _obj$nextReviewAt = react::bridging::fromJs<double>(rt, obj$nextReviewAt, callInvoker);

    craby::glimpsecore::bridging::GlimpseCalculateNextReviewOutput ret = {
      _obj$intervalMs,
      _obj$nextReviewAt
    };

    return ret;
  }

  static jsi::Value toJs(
      jsi::Runtime &rt,
      craby::glimpsecore::bridging::GlimpseCalculateNextReviewOutput value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$intervalMs = react::bridging::toJs(rt, value.interval_ms);
    auto _obj$nextReviewAt = react::bridging::toJs(rt, value.next_review_at);

    obj.setProperty(rt, "intervalMs", _obj$intervalMs);
    obj.setProperty(rt, "nextReviewAt", _obj$nextReviewAt);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::glimpsecore::bridging::GlimpseInitializeReviewScheduleOutput> {
  static craby::glimpsecore::bridging::GlimpseInitializeReviewScheduleOutput fromJs(
      jsi::Runtime &rt,
      const jsi::Value &value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$nextReviewAt = obj.getProperty(rt, "nextReviewAt");
    auto obj$stability = obj.getProperty(rt, "stability");
    auto obj$difficulty = obj.getProperty(rt, "difficulty");
    auto obj$lastReviewedAt = obj.getProperty(rt, "lastReviewedAt");

    auto _obj$nextReviewAt = react::bridging::fromJs<double>(rt, obj$nextReviewAt, callInvoker);
    auto _obj$stability = obj$stability.isNull()
        ? craby::glimpsecore::bridging::NullableNumber{true, 0.0}
        : craby::glimpsecore::bridging::NullableNumber{
            false,
            react::bridging::fromJs<double>(rt, obj$stability, callInvoker)};
    auto _obj$difficulty = obj$difficulty.isNull()
        ? craby::glimpsecore::bridging::NullableNumber{true, 0.0}
        : craby::glimpsecore::bridging::NullableNumber{
            false,
            react::bridging::fromJs<double>(rt, obj$difficulty, callInvoker)};
    auto _obj$lastReviewedAt = obj$lastReviewedAt.isNull()
        ? craby::glimpsecore::bridging::NullableNumber{true, 0.0}
        : craby::glimpsecore::bridging::NullableNumber{
            false,
            react::bridging::fromJs<double>(rt, obj$lastReviewedAt, callInvoker)};

    craby::glimpsecore::bridging::GlimpseInitializeReviewScheduleOutput ret = {
      _obj$nextReviewAt,
      _obj$stability,
      _obj$difficulty,
      _obj$lastReviewedAt
    };

    return ret;
  }

  static jsi::Value toJs(
      jsi::Runtime &rt,
      craby::glimpsecore::bridging::GlimpseInitializeReviewScheduleOutput value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$nextReviewAt = react::bridging::toJs(rt, value.next_review_at);
    auto _obj$stability = value.stability.null
        ? jsi::Value::null()
        : react::bridging::toJs(rt, value.stability.val, callInvoker);
    auto _obj$difficulty = value.difficulty.null
        ? jsi::Value::null()
        : react::bridging::toJs(rt, value.difficulty.val, callInvoker);
    auto _obj$lastReviewedAt = value.last_reviewed_at.null
        ? jsi::Value::null()
        : react::bridging::toJs(rt, value.last_reviewed_at.val, callInvoker);

    obj.setProperty(rt, "nextReviewAt", _obj$nextReviewAt);
    obj.setProperty(rt, "stability", _obj$stability);
    obj.setProperty(rt, "difficulty", _obj$difficulty);
    obj.setProperty(rt, "lastReviewedAt", _obj$lastReviewedAt);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::glimpsecore::bridging::NullableNumber> {
  static craby::glimpsecore::bridging::NullableNumber fromJs(
      jsi::Runtime &rt,
      const jsi::Value &value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    if (value.isNull()) {
      return craby::glimpsecore::bridging::NullableNumber{true, 0.0};
    }

    auto val = react::bridging::fromJs<double>(rt, value, callInvoker);
    auto ret = craby::glimpsecore::bridging::NullableNumber{false, val};

    return ret;
  }

  static jsi::Value toJs(
      jsi::Runtime &rt,
      craby::glimpsecore::bridging::NullableNumber value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    if (value.null) {
      return jsi::Value::null();
    }

    return react::bridging::toJs(rt, value.val);
  }
};

template <>
struct Bridging<craby::glimpsecore::bridging::NullableStringArray> {
  static craby::glimpsecore::bridging::NullableStringArray fromJs(
      jsi::Runtime &rt,
      const jsi::Value &value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    if (value.isNull()) {
      return craby::glimpsecore::bridging::NullableStringArray{true, rust::Vec<rust::String>()};
    }

    auto val = react::bridging::fromJs<rust::Vec<rust::String>>(rt, value, callInvoker);
    auto ret = craby::glimpsecore::bridging::NullableStringArray{false, val};

    return ret;
  }

  static jsi::Value toJs(
      jsi::Runtime &rt,
      craby::glimpsecore::bridging::NullableStringArray value,
      const std::shared_ptr<CallInvoker> &callInvoker) {
    if (value.null) {
      return jsi::Value::null();
    }

    return react::bridging::toJs(rt, value.val);
  }
};

} // namespace react
} // namespace facebook
