// Auto generated by Craby. DO NOT EDIT.
#include "CxxGlimpseCoreModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace glimpsecore {
namespace modules {

std::string CxxGlimpseCoreModule::dataPath = std::string();

CxxGlimpseCoreModule::CxxGlimpseCoreModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxGlimpseCoreModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::glimpsecore::bridging::GlimpseCore>(
    craby::glimpsecore::bridging::createGlimpseCore(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::glimpsecore::bridging::GlimpseCore *ptr) { rust::Box<craby::glimpsecore::bridging::GlimpseCore>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::glimpsecore::utils::ThreadPool>(10);
  methodMap_["calculateNextReview"] = MethodMetadata{4, &CxxGlimpseCoreModule::calculateNextReview};
  methodMap_["calculateTagOverlap"] = MethodMetadata{2, &CxxGlimpseCoreModule::calculateTagOverlap};
  methodMap_["initializeReviewSchedule"] = MethodMetadata{2, &CxxGlimpseCoreModule::initializeReviewSchedule};
}

CxxGlimpseCoreModule::~CxxGlimpseCoreModule() {
  invalidate();
}

void CxxGlimpseCoreModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxGlimpseCoreModule::calculateNextReview(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (4 != count) {
      throw jsi::JSError(rt, "Expected 4 arguments");
    }

    auto arg0 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[1], callInvoker);
    auto arg2$raw = args[2].asString(rt).utf8(rt);
    auto arg2 = rust::Str(arg2$raw.data(), arg2$raw.size());
    auto arg3 = react::bridging::fromJs<double>(rt, args[3], callInvoker);
    auto ret = craby::glimpsecore::bridging::calculateNextReview(*it_, arg0, arg1, arg2, arg3);

    return react::bridging::toJs(rt, ret, callInvoker);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::calculateTagOverlap(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableStringArray>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableStringArray>(rt, args[1], callInvoker);
    auto ret = craby::glimpsecore::bridging::calculateTagOverlap(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret, callInvoker);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

jsi::Value CxxGlimpseCoreModule::initializeReviewSchedule(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxGlimpseCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<craby::glimpsecore::bridging::NullableNumber>(rt, args[1], callInvoker);
    auto ret = craby::glimpsecore::bridging::initializeReviewSchedule(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret, callInvoker);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::glimpsecore::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace glimpsecore
} // namespace craby
