[package]
name = "glimpsecore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
cxx = { version = "1.0.187", features = ["c++20"] }
glimpse-core-rs = { path = "../../../../../../packages/core-rs" }
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "glimpsecore"
crate-type = ["staticlib"]
