export const messages = {
  ko: {
    common: {
      back: '뒤로 가기',
      cancel: '취소',
    },
    settings: {
      title: '설정',
      languageTitle: '언어',
      languageFooter: '언어 변경은 즉시 적용되고 이 기기에 저장됩니다',
      korean: '한국어',
      english: 'English',
      secureStorageNote:
        'ⓘ API 키는 기기의 보안 저장소에, 나머지 BYOK 설정은 로컬 저장소에 저장됩니다.\n화면에는 마스킹된 키만 표시되며, Base URL override는 현재 OpenAI provider에서만 적용됩니다.',
      exportDoneTitle: '내보내기 완료',
      exportDoneMessage: 'Glimpse 데이터 JSON을 클립보드에 복사했습니다.',
      exportFailedTitle: '내보내기 실패',
      importConfirmTitle: '클립보드 데이터로 교체할까요?',
      importConfirmMessage:
        '현재 보관함과 대화 기록을 먼저 내보내 두는 것을 권장합니다. 가져오기는 검증에 통과한 뒤 한 번에 적용됩니다.',
      importAction: '가져오기',
      importDoneTitle: '가져오기 완료',
      importFailedTitle: '가져오기 실패',
      deleteConfirmTitle: '보관함과 대화를 모두 삭제할까요?',
      deleteConfirmMessage:
        '이 작업은 되돌릴 수 없습니다. 설정, API 키, 다운로드한 모델 파일은 유지됩니다.',
      deleteAction: '모두 삭제',
      deleteDoneTitle: '삭제 완료',
      deleteDoneMessage: '보관함, 대화, 추천 기록을 모두 삭제했습니다.',
      deleteFailedTitle: '삭제 실패',
      unknownError: '알 수 없는 오류가 발생했습니다.',
      importedSummary: (knowledgeItems: number, conversations: number, itemMessages: number) =>
        `보관함 ${knowledgeItems}개, 대화 ${conversations}개, 메시지 ${itemMessages}개를 복원했습니다.`,
      reviewReminderTitle: '복습 알림',
      reviewReminderFooter: '매일 지정한 시간에 복습할 항목 수를 알려드립니다',
      reviewReminderEnable: '매일 알려드리기',
      reviewReminderTime: '알림 시간',
      reviewReminderDenied: '알림 권한이 꺼져 있어요. 시스템 설정에서 허용해 주세요',
      reviewReminderHour: '시간',
      reviewReminderMinute: '분',
      reviewReminderIncrease: '증가',
      reviewReminderDecrease: '감소',
      presetMorning: '오전 9:00',
      presetAfternoon: '오후 1:00',
      presetEvening: '오후 8:00 (추천)',
      presetCustom: '직접 설정',
      sectionAi: 'AI & 지능',
      sectionGeneral: '일반 & 알림',
      sectionSyncAndData: '기기 연동 & 데이터',
      aiOverviewTitle: '현재 AI 엔진',
      aiOverviewAuto: '스마트 자동 최적화',
      aiOverviewAutoDesc: '기기 사양에 맞춰 최적의 엔진이 자동으로 동작합니다.',
      aiOverviewApple: 'Apple Intelligence',
      aiOverviewAppleDesc: '온디바이스 기초 모델로 빠르고 안전하게 처리합니다.',
      aiOverviewLocal: '기기 내 로컬 모델',
      aiOverviewLocalDesc: '오프라인 상태에서도 기기 내에서 100% 안전하게 동작합니다.',
      aiOverviewByok: '외부 API 키',
      aiOverviewByokDesc: (provider: string) => `${provider} 모델로 고성능 AI 기능을 실행합니다.`,
      aiOverviewRules: '스마트 규칙 모드',
      aiOverviewRulesDesc: 'API 키나 모델 다운로드 없이 빠르고 가볍게 처리합니다.',
      aiModeSmart: '스마트 자동',
      aiModeSmartDesc: '기기 환경에 맞춰 가장 빠르고 적합한 엔진을 자동 선택합니다.',
      aiModeOnDevice: '프라이빗 온디바이스',
      aiModeOnDeviceDesc: '인터넷 없이 기기 내에서만 안전하게 동작 (Apple Intelligence / 로컬 모델)',
      aiModeCloud: '외부 API 키 직접 연결',
      aiModeCloudDesc: 'OpenAI, Claude, Gemini 등 보유한 API 키로 최고 성능 활용',
      recommendedBadge: '추천',
      semanticSearchTitle: '스마트 의미 검색',
      semanticSearchSubtitle: '정확한 키워드가 달라도 문맥과 의미로 메모를 찾습니다',
      advancedAiTitle: '고급 AI 설정 (기능별 세부 분기)',
      advancedAiNote: '기본 설정만으로도 최적으로 동작합니다. 특정 기능만 다른 모델로 처리하고 싶을 때 변경하세요.',
      manageLocalModels: '로컬 모델 관리 및 다운로드',
    },
    data: {
      title: '데이터 관리',
      footer: '내보내기에는 보관함, 대화, 추천 기록이 포함되며 API 키와 모델 파일은 포함되지 않습니다',
      exportTitle: 'JSON을 클립보드로 내보내기',
      exportDescription: '다른 기기나 백업 위치에 붙여넣을 수 있습니다',
      importTitle: '클립보드 JSON 가져오기',
      importDescription: '현재 보관함과 대화 기록을 검증된 백업으로 교체합니다',
      deleteTitle: '보관함과 대화 기록 모두 삭제',
      deleteDescription: '설정, API 키, 다운로드한 모델 파일은 유지됩니다',
      busyLabel: (title: string) => `${title} 진행 중`,
    },
  },
  en: {
    common: {
      back: 'Go back',
      cancel: 'Cancel',
    },
    settings: {
      title: 'Settings',
      languageTitle: 'Language',
      languageFooter: 'Language changes apply immediately and are saved on this device',
      korean: '한국어',
      english: 'English',
      secureStorageNote:
        'ⓘ API keys are kept in secure device storage; other BYOK settings stay in local storage.\nOnly masked keys are shown. The Base URL override currently applies only to the OpenAI provider.',
      exportDoneTitle: 'Export complete',
      exportDoneMessage: 'Copied the Glimpse data JSON to the clipboard.',
      exportFailedTitle: 'Export failed',
      importConfirmTitle: 'Replace data from the clipboard?',
      importConfirmMessage:
        'Export your current library and chats first. Import validates the backup before replacing data atomically.',
      importAction: 'Import',
      importDoneTitle: 'Import complete',
      importFailedTitle: 'Import failed',
      deleteConfirmTitle: 'Delete the library and all chats?',
      deleteConfirmMessage:
        'This cannot be undone. Settings, API keys, and downloaded model files are preserved.',
      deleteAction: 'Delete all',
      deleteDoneTitle: 'Deletion complete',
      deleteDoneMessage: 'Deleted the library, chats, and recommendation history.',
      deleteFailedTitle: 'Deletion failed',
      unknownError: 'An unknown error occurred.',
      importedSummary: (knowledgeItems: number, conversations: number, itemMessages: number) =>
        `Restored ${knowledgeItems} library items, ${conversations} chats, and ${itemMessages} messages.`,
      reviewReminderTitle: 'Review reminders',
      reviewReminderFooter: 'Daily digest of items due for review at your chosen time',
      reviewReminderEnable: 'Notify me daily',
      reviewReminderTime: 'Reminder time',
      reviewReminderDenied: 'Notifications are blocked. Enable them in system settings',
      reviewReminderHour: 'Hour',
      reviewReminderMinute: 'Minute',
      reviewReminderIncrease: 'Increase',
      reviewReminderDecrease: 'Decrease',
      presetMorning: '9:00 AM',
      presetAfternoon: '1:00 PM',
      presetEvening: '8:00 PM (Recommended)',
      presetCustom: 'Custom',
      sectionAi: 'AI & Intelligence',
      sectionGeneral: 'General & Notifications',
      sectionSyncAndData: 'Sync & Data',
      aiOverviewTitle: 'Current AI Engine',
      aiOverviewAuto: 'Smart Auto Optimization',
      aiOverviewAutoDesc: 'Optimal engine is automatically selected based on device performance.',
      aiOverviewApple: 'Apple Intelligence',
      aiOverviewAppleDesc: 'Fast, secure, and private on-device Foundation Model.',
      aiOverviewLocal: 'On-Device Local Model',
      aiOverviewLocalDesc: 'Runs 100% privately and securely on device even offline.',
      aiOverviewByok: 'External API Key',
      aiOverviewByokDesc: (provider: string) => `Powered by ${provider} high-performance cloud model.`,
      aiOverviewRules: 'Smart Rule Mode',
      aiOverviewRulesDesc: 'Lightweight and fast without requiring API keys or downloads.',
      aiModeSmart: 'Smart Auto',
      aiModeSmartDesc: 'Automatically picks the best available engine for your phone.',
      aiModeOnDevice: 'Private On-Device',
      aiModeOnDeviceDesc: 'Runs 100% on device with zero cloud data transfer (Apple Intelligence / Local LLM)',
      aiModeCloud: 'External API Key (BYOK)',
      aiModeCloudDesc: 'Connect OpenAI, Claude, or Gemini for maximum intelligence',
      recommendedBadge: 'Recommended',
      semanticSearchTitle: 'Smart Semantic Search',
      semanticSearchSubtitle: 'Find notes by context and meaning, not just exact keywords',
      advancedAiTitle: 'Advanced AI Routing (Per-feature)',
      advancedAiNote: 'Sensible defaults are already active. Only customize if you need specific models for separate features.',
      manageLocalModels: 'Manage & Download Local Models',
    },
    data: {
      title: 'Data management',
      footer: 'Exports include the library, chats, and recommendation history, but not API keys or model files',
      exportTitle: 'Copy JSON export',
      exportDescription: 'Paste it on another device or into your backup location',
      importTitle: 'Import clipboard JSON',
      importDescription: 'Replace the current library and chats with a validated backup',
      deleteTitle: 'Delete library and chat history',
      deleteDescription: 'Settings, API keys, and downloaded models are preserved',
      busyLabel: (title: string) => `${title} in progress`,
    },
  },
} as const;

export type AppLocale = keyof typeof messages;
export type AppMessages = (typeof messages)[AppLocale];
